/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 houston_texas_usa.glb --transform 
Files: houston_texas_usa.glb [15.43MB] > /Users/streisenberg/Documents/GitHub/PersonalWebsite/public/assets/houston_texas_usa-transformed.glb [846.7KB] (95%)
Author: jack.simmons (https://sketchfab.com/jack.simmons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/houston-texas-usa-53f2709009f54dcfb258e1ea28ed8831
Title: Houston, Texas, USA
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/houston_texas_usa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.EXPORT_ESRI_TOPO_WM_rastMat001_0.geometry} material={materials['rastMat.001']} position={[-23.702, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.04, 1.04, 1]} />
      <mesh geometry={nodes.Wayshighway__0.geometry} material={materials.Wayshighway__0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/houston_texas_usa-transformed.glb')
