/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 maidens_tower.glb --transform 
Files: maidens_tower.glb [8.64MB] > /Users/streisenberg/Documents/GitHub/PersonalWebsite/public/assets/maidens_tower-transformed.glb [369.11KB] (96%)
Author: Erbay Çelik (https://sketchfab.com/erbaycelik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/maidens-tower-37f24564b1c446e7b2e99d5ae635ceda
Title: Maiden's Tower
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/maidens_tower-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCube21_marti_tur_0.geometry} material={materials.PaletteMaterial001} position={[1.303, 1.381, -0.137]} rotation={[0, -0.309, 0]} scale={[0.004, 0.006, 0.004]} />
      <mesh geometry={nodes.pCube23_blinn1_0.geometry} material={materials.PaletteMaterial002} scale={0.01} />
      <mesh geometry={nodes.pCylinder2_dirt_0.geometry} material={materials.dirt} scale={0.01} />
      <mesh geometry={nodes.deniz1_deniz_0.geometry} material={materials.deniz} position={[0, -2.266, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/maidens_tower-transformed.glb')
