/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ship_in_clouds.glb --transform 
Files: ship_in_clouds.glb [7.98MB] > /Users/streisenberg/Documents/GitHub/PersonalWebsite/public/assets/ship_in_clouds-transformed.glb [1.64MB] (80%)
Author: Bastien Genbrugge (https://sketchfab.com/bastienBGR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ship-in-clouds-c475323dc7f24e26ba2009c08c8e1941
Title: Ship in Clouds
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ship_in_clouds-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sky_Mat_0.geometry} material={materials.material} position={[0.177, 0, -2.802]} rotation={[0, -Math.PI / 2, 0]} scale={0.003} />
      <mesh geometry={nodes.Boot_Finaal_1_Boot_Finaal_0.geometry} material={materials.Boot_Finaal} position={[0.026, -0.027, -2.36]} rotation={[0, -0.6, 0]} scale={0.003} />
      <mesh geometry={nodes.Cloud_Poly_Poly_0.geometry} material={materials.Poly} scale={0.003} />
      <mesh geometry={nodes.Cloud_1_Cloud_1_0.geometry} material={materials.Cloud_1} position={[-0.351, -0.521, -4.147]} rotation={[1.917, 0.433, 0.911]} scale={0.005} />
      <mesh geometry={nodes.Cloud_2_Cloud_2_0.geometry} material={materials.Cloud_2} position={[1.142, -0.219, -5.284]} rotation={[-2.901, 0.214, -1.167]} scale={0.005} />
      <mesh geometry={nodes.Cloud_3_Cloud_3_0.geometry} material={materials.Cloud_3} position={[1.163, -0.243, -5.387]} rotation={[2.892, -1.308, 3.083]} scale={0.004} />
    </group>
  )
}

useGLTF.preload('/ship_in_clouds-transformed.glb')
