/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 taksim_tunel.glb --transform 
Files: taksim_tunel.glb [35.98MB] > /Users/streisenberg/Documents/GitHub/PersonalWebsite/public/assets/taksim_tunel-transformed.glb [4.29MB] (88%)
Author: Gürkan GÜRBÜZ (https://sketchfab.com/gg2912)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/taksim-tunel-d62dd0c0ef274cfc8b92609d1ec5e84a
Title: Taksim Tunel
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/taksim_tunel-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.052}>
          <group name="Group55535" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group55535_woman_0" geometry={nodes.Group55535_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group43557" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group43557_woman_0" geometry={nodes.Group43557_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group34675" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group34675_woman_0" geometry={nodes.Group34675_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group34676" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group34676_woman_0" geometry={nodes.Group34676_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group34677" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group34677_woman_0" geometry={nodes.Group34677_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group34678" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group34678_woman_0" geometry={nodes.Group34678_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group34681" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group34681_woman_0" geometry={nodes.Group34681_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group34682" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group34682_woman_0" geometry={nodes.Group34682_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group34683" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group34683_woman_0" geometry={nodes.Group34683_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group34684" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group34684_woman_0" geometry={nodes.Group34684_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="Group34688" position={[31.615, 23.308, -15.834]} rotation={[-Math.PI / 2, 0, 3.012]} scale={17.115}>
            <mesh name="Group34688_woman_0" geometry={nodes.Group34688_woman_0.geometry} material={materials.woman} />
          </group>
          <group name="ceptel" position={[33.909, 28.018, -21.14]} rotation={[-1.351, -0.345, 2.668]} scale={0.272}>
            <mesh name="ceptel_ceptel_0" geometry={nodes.ceptel_ceptel_0.geometry} material={materials.ceptel} />
          </group>
          <group name="semdi" position={[27.807, 38.65, -17.79]} rotation={[-Math.PI / 2, 0, 3.012]} scale={0.354}>
            <mesh name="semdi_semdi_0" geometry={nodes.semdi_semdi_0.geometry} material={materials.semdi} />
          </group>
        </group>
        <group name="rainover" position={[0.067, 2.691, -0.37]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052}>
          <group name="BakedParticleMesh_032" position={[-33.678, -70.577, -18.338]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_032_rain_0" geometry={nodes.BakedParticleMesh_032_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_038" position={[-44.607, -52.677, 0.862]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_038_rain_0" geometry={nodes.BakedParticleMesh_038_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_044" position={[-42.438, 33.626, 16.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_044_rain_0" geometry={nodes.BakedParticleMesh_044_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_047" position={[-44.972, 68.075, -44.904]}>
            <mesh name="BakedParticleMesh_047_rain_0" geometry={nodes.BakedParticleMesh_047_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_051" position={[3.111, -4.425, 13.297]}>
            <mesh name="BakedParticleMesh_051_rain_0" geometry={nodes.BakedParticleMesh_051_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_055" position={[39.073, 14.795, 28.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_055_rain_0" geometry={nodes.BakedParticleMesh_055_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_056" position={[-19.445, -13.207, -44.769]}>
            <mesh name="BakedParticleMesh_056_rain_0" geometry={nodes.BakedParticleMesh_056_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_057" position={[-16.92, -11.731, -44.858]}>
            <mesh name="BakedParticleMesh_057_rain_0" geometry={nodes.BakedParticleMesh_057_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_058" position={[-16.973, -15.091, -44.869]}>
            <mesh name="BakedParticleMesh_058_rain_0" geometry={nodes.BakedParticleMesh_058_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_059" position={[-19.098, -13.519, -44.883]}>
            <mesh name="BakedParticleMesh_059_rain_0" geometry={nodes.BakedParticleMesh_059_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_060" position={[-14.175, -7.792, -44.856]}>
            <mesh name="BakedParticleMesh_060_rain_0" geometry={nodes.BakedParticleMesh_060_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_061" position={[15.982, -55.682, 36.862]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_061_rain_0" geometry={nodes.BakedParticleMesh_061_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_062" position={[27.344, 34.33, -44.881]}>
            <mesh name="BakedParticleMesh_062_rain_0" geometry={nodes.BakedParticleMesh_062_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_063" position={[30.601, 37.577, -44.891]}>
            <mesh name="BakedParticleMesh_063_rain_0" geometry={nodes.BakedParticleMesh_063_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_064" position={[30.783, 32.899, -44.882]}>
            <mesh name="BakedParticleMesh_064_rain_0" geometry={nodes.BakedParticleMesh_064_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_065" position={[27.793, 37.207, -44.882]}>
            <mesh name="BakedParticleMesh_065_rain_0" geometry={nodes.BakedParticleMesh_065_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_066" position={[28.187, 32.758, -44.917]}>
            <mesh name="BakedParticleMesh_066_rain_0" geometry={nodes.BakedParticleMesh_066_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_067" position={[28.405, 70.783, 41.662]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_067_rain_0" geometry={nodes.BakedParticleMesh_067_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_068" position={[-9.988, -35.021, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_068_rain_0" geometry={nodes.BakedParticleMesh_068_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_069" position={[-33.58, -3.675, -44.882]}>
            <mesh name="BakedParticleMesh_069_rain_0" geometry={nodes.BakedParticleMesh_069_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_070" position={[-33.321, -3.752, -44.694]}>
            <mesh name="BakedParticleMesh_070_rain_0" geometry={nodes.BakedParticleMesh_070_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_071" position={[-33.265, -3.669, -44.592]}>
            <mesh name="BakedParticleMesh_071_rain_0" geometry={nodes.BakedParticleMesh_071_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_072" position={[-33.52, -3.705, -44.819]}>
            <mesh name="BakedParticleMesh_072_rain_0" geometry={nodes.BakedParticleMesh_072_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_073" position={[-33.601, -3.76, -44.86]}>
            <mesh name="BakedParticleMesh_073_rain_0" geometry={nodes.BakedParticleMesh_073_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_074" position={[31.233, -56.774, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_074_rain_0" geometry={nodes.BakedParticleMesh_074_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_075" position={[-33.564, -70.243, -44.477]}>
            <mesh name="BakedParticleMesh_075_rain_0" geometry={nodes.BakedParticleMesh_075_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_076" position={[-33.788, -71.048, -44.6]}>
            <mesh name="BakedParticleMesh_076_rain_0" geometry={nodes.BakedParticleMesh_076_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_077" position={[-33.936, -70.283, -44.919]}>
            <mesh name="BakedParticleMesh_077_rain_0" geometry={nodes.BakedParticleMesh_077_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_078" position={[-33.764, -70.602, -44.45]}>
            <mesh name="BakedParticleMesh_078_rain_0" geometry={nodes.BakedParticleMesh_078_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_079" position={[-33.416, -70.919, -44.617]}>
            <mesh name="BakedParticleMesh_079_rain_0" geometry={nodes.BakedParticleMesh_079_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_080" position={[46.159, 0.526, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_080_rain_0" geometry={nodes.BakedParticleMesh_080_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_081" position={[-44.802, -52.802, -44.251]}>
            <mesh name="BakedParticleMesh_081_rain_0" geometry={nodes.BakedParticleMesh_081_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_082" position={[-44.652, -52.774, -44.315]}>
            <mesh name="BakedParticleMesh_082_rain_0" geometry={nodes.BakedParticleMesh_082_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_083" position={[-45.069, -52.494, -44.377]}>
            <mesh name="BakedParticleMesh_083_rain_0" geometry={nodes.BakedParticleMesh_083_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_084" position={[-44.729, -52.691, -44.394]}>
            <mesh name="BakedParticleMesh_084_rain_0" geometry={nodes.BakedParticleMesh_084_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_085" position={[-44.097, -52.574, -44.545]}>
            <mesh name="BakedParticleMesh_085_rain_0" geometry={nodes.BakedParticleMesh_085_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_086" position={[13.631, 50.718, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_086_rain_0" geometry={nodes.BakedParticleMesh_086_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_087" position={[-42.625, 34.292, -44.584]}>
            <mesh name="BakedParticleMesh_087_rain_0" geometry={nodes.BakedParticleMesh_087_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_088" position={[-42.477, 33.575, -44.334]}>
            <mesh name="BakedParticleMesh_088_rain_0" geometry={nodes.BakedParticleMesh_088_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_089" position={[-42.28, 34.335, -44.563]}>
            <mesh name="BakedParticleMesh_089_rain_0" geometry={nodes.BakedParticleMesh_089_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_090" position={[-42.927, 33.211, -44.679]}>
            <mesh name="BakedParticleMesh_090_rain_0" geometry={nodes.BakedParticleMesh_090_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_091" position={[-42.641, 34.019, -44.246]}>
            <mesh name="BakedParticleMesh_091_rain_0" geometry={nodes.BakedParticleMesh_091_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_092" position={[10.226, -45.664, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_092_rain_0" geometry={nodes.BakedParticleMesh_092_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_093" position={[39.27, 14.829, -44.629]}>
            <mesh name="BakedParticleMesh_093_rain_0" geometry={nodes.BakedParticleMesh_093_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_094" position={[39.01, 15.128, -44.647]}>
            <mesh name="BakedParticleMesh_094_rain_0" geometry={nodes.BakedParticleMesh_094_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_095" position={[39.185, 14.66, -44.584]}>
            <mesh name="BakedParticleMesh_095_rain_0" geometry={nodes.BakedParticleMesh_095_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_096" position={[39.428, 14.769, -44.685]}>
            <mesh name="BakedParticleMesh_096_rain_0" geometry={nodes.BakedParticleMesh_096_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_097" position={[38.989, 15.143, -44.799]}>
            <mesh name="BakedParticleMesh_097_rain_0" geometry={nodes.BakedParticleMesh_097_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_098" position={[-9.88, -35.114, 12.185]}>
            <mesh name="BakedParticleMesh_098_rain_0" geometry={nodes.BakedParticleMesh_098_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_099" position={[-10.258, -34.74, 12.257]}>
            <mesh name="BakedParticleMesh_099_rain_0" geometry={nodes.BakedParticleMesh_099_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_100" position={[-10.039, -35.296, 12.283]}>
            <mesh name="BakedParticleMesh_100_rain_0" geometry={nodes.BakedParticleMesh_100_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_101" position={[-11.011, -34.747, 11.988]}>
            <mesh name="BakedParticleMesh_101_rain_0" geometry={nodes.BakedParticleMesh_101_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_102" position={[-10.821, -34.03, 12.124]}>
            <mesh name="BakedParticleMesh_102_rain_0" geometry={nodes.BakedParticleMesh_102_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_103" position={[2.624, -45.103, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_103_rain_0" geometry={nodes.BakedParticleMesh_103_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_104" position={[15.598, -55.497, -44.615]}>
            <mesh name="BakedParticleMesh_104_rain_0" geometry={nodes.BakedParticleMesh_104_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_105" position={[15.905, -55.514, -44.404]}>
            <mesh name="BakedParticleMesh_105_rain_0" geometry={nodes.BakedParticleMesh_105_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_106" position={[16.077, -55.585, -44.432]}>
            <mesh name="BakedParticleMesh_106_rain_0" geometry={nodes.BakedParticleMesh_106_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_107" position={[15.63, -55.29, -44.746]}>
            <mesh name="BakedParticleMesh_107_rain_0" geometry={nodes.BakedParticleMesh_107_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_108" position={[15.766, -55.341, -44.844]}>
            <mesh name="BakedParticleMesh_108_rain_0" geometry={nodes.BakedParticleMesh_108_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_109" position={[8.485, 0.976, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_109_rain_0" geometry={nodes.BakedParticleMesh_109_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_110" position={[28.415, 70.736, -44.561]}>
            <mesh name="BakedParticleMesh_110_rain_0" geometry={nodes.BakedParticleMesh_110_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_111" position={[28.323, 70.934, -44.475]}>
            <mesh name="BakedParticleMesh_111_rain_0" geometry={nodes.BakedParticleMesh_111_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_112" position={[28.549, 70.636, -44.492]}>
            <mesh name="BakedParticleMesh_112_rain_0" geometry={nodes.BakedParticleMesh_112_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_113" position={[28.867, 70.576, -44.67]}>
            <mesh name="BakedParticleMesh_113_rain_0" geometry={nodes.BakedParticleMesh_113_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_114" position={[28.34, 71.031, -44.655]}>
            <mesh name="BakedParticleMesh_114_rain_0" geometry={nodes.BakedParticleMesh_114_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_115" position={[-33.545, 58.952, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_115_rain_0" geometry={nodes.BakedParticleMesh_115_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_116" position={[-46.548, 21.51, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_116_rain_0" geometry={nodes.BakedParticleMesh_116_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_117" position={[30.777, -56.419, -44.458]}>
            <mesh name="BakedParticleMesh_117_rain_0" geometry={nodes.BakedParticleMesh_117_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_118" position={[31.469, -56.66, -44.287]}>
            <mesh name="BakedParticleMesh_118_rain_0" geometry={nodes.BakedParticleMesh_118_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_119" position={[30.769, -56.685, -44.461]}>
            <mesh name="BakedParticleMesh_119_rain_0" geometry={nodes.BakedParticleMesh_119_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_120" position={[31.896, -56.583, -44.601]}>
            <mesh name="BakedParticleMesh_120_rain_0" geometry={nodes.BakedParticleMesh_120_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_121" position={[31.305, -56.228, -44.695]}>
            <mesh name="BakedParticleMesh_121_rain_0" geometry={nodes.BakedParticleMesh_121_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_122" position={[10.09, -45.992, 11.967]}>
            <mesh name="BakedParticleMesh_122_rain_0" geometry={nodes.BakedParticleMesh_122_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_123" position={[9.872, -45.806, 12.613]}>
            <mesh name="BakedParticleMesh_123_rain_0" geometry={nodes.BakedParticleMesh_123_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_124" position={[9.646, -45.89, 12.169]}>
            <mesh name="BakedParticleMesh_124_rain_0" geometry={nodes.BakedParticleMesh_124_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_125" position={[9.877, -45.373, 12.407]}>
            <mesh name="BakedParticleMesh_125_rain_0" geometry={nodes.BakedParticleMesh_125_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_126" position={[9.864, -45.401, 12.021]}>
            <mesh name="BakedParticleMesh_126_rain_0" geometry={nodes.BakedParticleMesh_126_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_127" position={[15.605, -26.141, 42.462]} scale={[0.005, 0.005, 0.51]}>
            <mesh name="BakedParticleMesh_127_rain_0" geometry={nodes.BakedParticleMesh_127_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_128" position={[46.45, 0.191, -44.635]}>
            <mesh name="BakedParticleMesh_128_rain_0" geometry={nodes.BakedParticleMesh_128_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_129" position={[46.296, -0.173, -44.897]}>
            <mesh name="BakedParticleMesh_129_rain_0" geometry={nodes.BakedParticleMesh_129_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_130" position={[46.141, 0.37, -44.335]}>
            <mesh name="BakedParticleMesh_130_rain_0" geometry={nodes.BakedParticleMesh_130_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_131" position={[46.489, 0.932, -44.781]}>
            <mesh name="BakedParticleMesh_131_rain_0" geometry={nodes.BakedParticleMesh_131_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_132" position={[46.375, 0.977, -44.76]}>
            <mesh name="BakedParticleMesh_132_rain_0" geometry={nodes.BakedParticleMesh_132_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_133" position={[3.604, -43.367, 11.057]}>
            <mesh name="BakedParticleMesh_133_rain_0" geometry={nodes.BakedParticleMesh_133_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_134" position={[1.424, -47.056, 11.242]}>
            <mesh name="BakedParticleMesh_134_rain_0" geometry={nodes.BakedParticleMesh_134_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_135" position={[2.689, -45.44, 12.352]}>
            <mesh name="BakedParticleMesh_135_rain_0" geometry={nodes.BakedParticleMesh_135_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_136" position={[2.75, -45.235, 11.998]}>
            <mesh name="BakedParticleMesh_136_rain_0" geometry={nodes.BakedParticleMesh_136_rain_0.geometry} material={materials.rain} />
          </group>
          <group name="BakedParticleMesh_137" position={[2.451, -45.15, 12.263]}>
            <mesh name="BakedParticleMesh_137_rain_0" geometry={nodes.BakedParticleMesh_137_rain_0.geometry} material={materials.rain} />
          </group>
        </group>
        <mesh name="Box016_zemin_0" geometry={nodes.Box016_zemin_0.geometry} material={materials.zemin} position={[0.378, 0.218, -0.491]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="Line009_bot_0" geometry={nodes.Line009_bot_0.geometry} material={materials.material} position={[-0.701, 0.519, 0.927]} rotation={[0, -Math.PI / 2, 0]} scale={0.052} />
        <mesh name="Object006_tabantavan_0" geometry={nodes.Object006_tabantavan_0.geometry} material={materials.tabantavan} position={[0.063, 2.875, 0.509]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.052} />
        <mesh name="Box010_koltuk_0" geometry={nodes.Box010_koltuk_0.geometry} material={materials.koltuk} position={[-0.433, 1.091, 0.399]} rotation={[-Math.PI / 2, 0, 0]} scale={0.059} />
        <mesh name="Object009_ara_0" geometry={nodes.Object009_ara_0.geometry} material={materials.material_5} position={[0.063, 1.091, 0.509]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="Object004_cablock_0" geometry={nodes.Object004_cablock_0.geometry} material={materials.cablock} position={[0.063, 1.091, 0.509]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="Line012_demir_0" geometry={nodes.Line012_demir_0.geometry} material={materials.demir} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="Plane001_yaprak_0" geometry={nodes.Plane001_yaprak_0.geometry} material={materials.yaprak} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="Group17952_Man_0" geometry={nodes.Group17952_Man_0.geometry} material={materials.material_9} position={[-2.201, 1.204, 2.334]} rotation={[-Math.PI / 2, 0, 1.436]} scale={0.866} />
        <mesh name="Box002_top_0" geometry={nodes.Box002_top_0.geometry} material={materials.material_12} position={[0.063, 1.214, 0.509]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="Box001_bottop_0" geometry={nodes.Box001_bottop_0.geometry} material={materials.bottop} position={[0.063, 1.091, 0.509]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="discephe_discephe_0" geometry={nodes.discephe_discephe_0.geometry} material={materials.discephe} position={[0.063, 1.091, 0.509]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="Box005_parts_0" geometry={nodes.Box005_parts_0.geometry} material={materials.parts} position={[-0.548, 3.12, 2.713]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="Sphere001__0" geometry={nodes.Sphere001__0.geometry} material={materials.Sphere001__0} position={[3.249, 0.399, 2.527]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
        <mesh name="seimdiye_semsiye_0" geometry={nodes.seimdiye_semsiye_0.geometry} material={materials.semsiye} position={[-2.05, 1.872, 2.259]} rotation={[-1.469, -0.405, 1.421]} scale={[0.019, 0.019, 0.016]} />
      </group>
    </group>
  )
}

useGLTF.preload('/taksim_tunel-transformed.glb')
