/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_white_tower_of_thessaloniki_greece.glb --transform 
Files: the_white_tower_of_thessaloniki_greece.glb [35.88MB] > /Users/streisenberg/Documents/GitHub/PersonalWebsite/public/assets/the_white_tower_of_thessaloniki_greece-transformed.glb [1.62MB] (95%)
Author: Nick G. Gizelis (https://sketchfab.com/aumakua)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-white-tower-of-thessaloniki-greece-c1185bd2f6824e1990d8b7e272505b1e
Title: The White Tower of Thessaloniki, Greece
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/the_white_tower_of_thessaloniki_greece-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} position={[-36.58, -15.846, 2.874]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/the_white_tower_of_thessaloniki_greece-transformed.glb')
